### ISSUE TITLE
Simulate translocations?

### ISSUE THREAD

**Issue by Madelinehazel** [bioinform/varsim#57]
Is it possible to simulate inter- and intra-chromosomal translocations?
If so, what is the correct way to annotate these in the VCF file(i.e. include the breakpoint on each chromosome)?

**Comment by marghoob** [comment]
Hi Madeline

Yes, we do support translocations but it is currently under heavy development, which is why there is no release yet. For an example of how this would be done, you can browse https://github.com/bioinform/varsim/tree/master/src/test/resources/TranslocationTest for test VCFs. We currently only have only entry in the VCF for each translocation--this entry corresponds to the destination of the cut/copy-paste event. In the future, we plan to do breakend-style (BND entries) in the VCF specification. In addition, currently our translocation support only does simulation and no validation of such events (we plan to address this this year).

Best
Marghoob.
